### PR TITLE
Update dependencies related to babel

### PR DESCRIPTION
**Pull request by emilos**
Hey,

thanks for the lib!

I was planning to add a PR to be able to render a custom input and I've spotted that the lib does not include tests. Would it be ok to pick `jest` and `enzyme`for it? I'd include few basic specs too.

In this PR I've updated dependencies related to babel so that it's easier to use `jest` in another PR.

I've used https://github.com/babel/babel-upgrade tool given that babel 6->7 migration is not that easy as it looks. All of the scripts in `package.json` are passing, the examples are working and the `build/index.js` file looks good. Is there anything else I should check?

### CODE REVIEW

**Comment by jacobmischka** [comment]
Looks good to me!

**Comment by haoxins** [comment]
@jacobmischka please kindly help to release a new version? I'm not beside my computer :)

**Comment by jacobmischka** [comment]
I'll be happy to, but do we need to? Is the build output better enough to justify one right now?

**Comment by haoxins** [comment]
yeah :)
no need IMO.

**Pull request merged**
