### PR TITLE
add esm and cjs build

### PR DESCRIPTION
**Pull request by cobalt-medma**
- add esm and cjs
- replace webpack with vite

NOTE:
I removed this line only because I couldn't make it work locally.
```json
    "eslint-config-ok": "github:haoxins/eslint-config",

```

### CODE REVIEW

**Comment by cobalt-medma** [comment]
Ey guys,

Could someone help me test that this is working? for me, it works and solves my issue. I'm not really sure you would want to do something like this but was easier to solve my issue this way than to do a workaround to it.

**Review by haoxins — APPROVED** [review]

**Comment by haoxins** [comment]
Because I'm not working on frontend any more. I can't find my NPM account back.
Maybe @jacobmischka can help to give you the NPM package access.

**Comment by jacobmischka** [comment]
Um I can publish the package I suppose, honestly would rather not grant access so quickly given this is your first commit here, apologies.

Why did you bump this to 4.0? Does this actually have breaking changes or is it just build tooling changes?

**Comment by haoxins** [comment]
> > 
> 
> Could you invite my personal account instead, please? @maxmedina05

done

**Pull request merged**
